version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run: ./node_modules/.bin/cypress open

orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@1.28.0

workflows:
  build_and_test:
    jobs:
      - test